import GSAP from '@/lib/gsap'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { Header } from '@/components/Header'
import PageTransition from '@/utils/PageTransition'

import './globals.scss'
import MouseFollower from '@/lib/CursorFollower'

const Publicsans = localFont({
  src: [
    {
      path: '../assets/fonts/PublicSans.woff2',
      weight: '100 900',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Publicsans-Italic.woff2',
      weight: '100 900',
      style: 'italic',
    },
  ],
  variable: '--font-public-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${Publicsans.variable} antialiased`}>
        <PageTransition>
          <GSAP>
            <Header />
            {children}
          </GSAP>
          <div id="scroll-progress" />
        </PageTransition>
        <MouseFollower />
      </body>
    </html>
  )
}
